import os

DEBUG = True
SECRET_KEY = os.urandom(24)

DB_USERNAME = 'root'
DB_PASSWORD = 'xjv123..'
DB_HOST = '127.0.0.1'
DB_PORT = '3306'
DB_NAME = 'zlbbs'
DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (DB_USERNAME, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

CMS_USER_ID = 'qwreqsaxcvvd'

MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = '587'
MAIL_USE_TLS = True
# MAIL_USE_SSL
MAIL_USERNAME = "xjv1195275315@qq.com"
MAIL_PASSWORD = "igtqeblbgaqyhgag"
MAIL_DEFAULT_SENDER = "xjv1195275315@qq.com"

ALIBABA_CLOUD_ACCESS_KEY_ID = 'LTAI5tMnrCjBgA6vd1B7oxZ2'
ALIBABA_CLOUD_ACCESS_KEY_SECRET = 'mTo6BPbCPnvEfufSSILoPubCFrR40z'
